 CREATE TABLE users (
ID BIGINT NOT NULL ,
SCREEN_NAME VARCHAR( 15 ) NOT NULL ,
NAME VARCHAR( 20 ) NOT NULL ,
URL VARCHAR( 300 ) NOT NULL ,
PROFILE_IMAGE_URL VARCHAR( 300 ) NOT NULL ,
DESCRIPTION VARCHAR( 160 ) NOT NULL ,
LOCATION VARCHAR( 100 ) NOT NULL ,
CREATED_DATE DATE NOT NULL ,
FAVORITES_COUNT INT NOT NULL ,
FOLLOWERS_COUNT INT NOT NULL ,
FRIENDS_COUNT INT NOT NULL ,
LANGUAGE VARCHAR( 100 ) NOT NULL ,
PROFILE_URL VARCHAR( 300 ) NOT NULL ,
STATUSES_COUNT INT NOT NULL ,
FITNESS_SCORE FLOAT NOT NULL ,
LAST_UPDATED DATE NOT NULL ,
PRIMARY KEY (ID)
);

