insert into users (id,
screen_name,
name,
url,
profile_image_url,
description,
location,
date,
favorites_count,
followers_count,
friends_count,
language,
profile_url,
statuses_count,
fitness_score,
last_updated) values (1234, 'lisaHalvors', 'Lisa Halvorsen', 'hppt://example.com/lisa', 
'hppt://example.com/lisa/img.png', 'description', 'Bergen', '2012-04-09', 4, 23, 43, 'Norwegian', 'http://twitter.com/lisaHalvors', 12, 64, '2012-04-09');

insert into users (id,
screen_name,
name,
url,
profile_image_url,
description,
location,
date,
favorites_count,
followers_count,
friends_count,
language,
profile_url,
statuses_count,
fitness_score,
last_updated) values (1111, 'torstein', 'Torstein Thune', 'hppt://example.com/torstein', 
'hppt://example.com/torstein/img.png', 'description', 'Bergen', '2012-04-09', 1, 22, 21, 'Norwegian', 'http://twitter.com/otsteinTune', 34, 97, '2012-04-09');
